const RESIZE_HANDLES: Array<"s" | "w" | "e" | "n" | "sw" | "nw" | "se" | "ne"> =
  ["s", "w", "e", "n", "sw", "nw", "se", "ne"];

// Min height constraint
const MIN_HEIGHT = 3; // minimum 3 rows

// Default layouts
export const DEFAULT_LAYOUTS = {
  lg: [
    {
      i: "1",
      x: 0,
      y: 0,
      w: 6,
      h: 3,
      maxW: 6,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
    {
      i: "2",
      x: 6,
      y: 0,
      w: 6,
      h: 3,
      maxW: 6,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
    {
      i: "3",
      x: 0,
      y: 3,
      w: 6,
      h: 3,
      maxW: 6,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
    {
      i: "4",
      x: 6,
      y: 3,
      w: 6,
      h: 3,
      maxW: 6,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
    {
      i: "5",
      x: 0,
      y: 6,
      w: 6,
      h: 3,
      maxW: 6,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
    {
      i: "6",
      x: 6,
      y: 6,
      w: 6,
      h: 3,
      maxW: 6,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
  ],
  md: [
    {
      i: "1",
      x: 0,
      y: 0,
      w: 5,
      h: 3,
      maxW: 5,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
    {
      i: "2",
      x: 5,
      y: 0,
      w: 5,
      h: 3,
      maxW: 5,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
    {
      i: "3",
      x: 0,
      y: 3,
      w: 5,
      h: 3,
      maxW: 5,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
    {
      i: "4",
      x: 5,
      y: 3,
      w: 5,
      h: 3,
      maxW: 5,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
    {
      i: "5",
      x: 0,
      y: 6,
      w: 5,
      h: 3,
      maxW: 5,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
    {
      i: "6",
      x: 5,
      y: 6,
      w: 5,
      h: 3,
      maxW: 5,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
  ],
  sm: [
    {
      i: "1",
      x: 0,
      y: 0,
      w: 6,
      h: 3,
      maxW: 6,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
    {
      i: "2",
      x: 0,
      y: 3,
      w: 6,
      h: 3,
      maxW: 6,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
    {
      i: "3",
      x: 0,
      y: 6,
      w: 6,
      h: 3,
      maxW: 6,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
    {
      i: "4",
      x: 0,
      y: 9,
      w: 6,
      h: 3,
      maxW: 6,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
    {
      i: "5",
      x: 0,
      y: 12,
      w: 6,
      h: 3,
      maxW: 6,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
    {
      i: "6",
      x: 0,
      y: 15,
      w: 6,
      h: 3,
      maxW: 6,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
  ],
  xs: [
    {
      i: "1",
      x: 0,
      y: 0,
      w: 4,
      h: 3,
      maxW: 4,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
    {
      i: "2",
      x: 0,
      y: 3,
      w: 4,
      h: 3,
      maxW: 4,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
    {
      i: "3",
      x: 0,
      y: 6,
      w: 4,
      h: 3,
      maxW: 4,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
    {
      i: "4",
      x: 0,
      y: 9,
      w: 4,
      h: 3,
      maxW: 4,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
    {
      i: "5",
      x: 0,
      y: 12,
      w: 4,
      h: 3,
      maxW: 4,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
    {
      i: "6",
      x: 0,
      y: 15,
      w: 4,
      h: 3,
      maxW: 4,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
  ],
  xxs: [
    {
      i: "1",
      x: 0,
      y: 0,
      w: 1,
      h: 3,
      maxW: 1,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
    {
      i: "2",
      x: 0,
      y: 3,
      w: 1,
      h: 3,
      maxW: 1,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
    {
      i: "3",
      x: 0,
      y: 6,
      w: 1,
      h: 3,
      maxW: 1,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
    {
      i: "4",
      x: 0,
      y: 9,
      w: 1,
      h: 3,
      maxW: 1,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
    {
      i: "5",
      x: 0,
      y: 12,
      w: 1,
      h: 3,
      maxW: 1,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
    {
      i: "6",
      x: 0,
      y: 15,
      w: 1,
      h: 3,
      maxW: 1,
      resizeHandles: RESIZE_HANDLES,
      minH: MIN_HEIGHT,
    },
  ],
};

// Max width constraints per breakpoint (using maxW prop)
const MAX_WIDTHS = {
  lg: 6, // 1/2 of 12 columns
  md: 5, // 1/2 of 10 columns
  sm: 6, // full width (all 6 columns)
  xs: 4, // full width (all 4 columns)
  xxs: 1, // full width (all 1 column)
};

// Helper function to add maxW, minH and resizeHandles to layout items
export const addMaxWToLayouts = (
  layouts: typeof DEFAULT_LAYOUTS
): typeof DEFAULT_LAYOUTS => {
  return {
    lg: layouts.lg.map((item) => ({
      ...item,
      maxW: MAX_WIDTHS.lg,
      minH: MIN_HEIGHT,
      resizeHandles: RESIZE_HANDLES,
    })),
    md: layouts.md.map((item) => ({
      ...item,
      maxW: MAX_WIDTHS.md,
      minH: MIN_HEIGHT,
      resizeHandles: RESIZE_HANDLES,
    })),
    sm: layouts.sm.map((item) => ({
      ...item,
      maxW: MAX_WIDTHS.sm,
      minH: MIN_HEIGHT,
      resizeHandles: RESIZE_HANDLES,
    })),
    xs: layouts.xs.map((item) => ({
      ...item,
      maxW: MAX_WIDTHS.xs,
      minH: MIN_HEIGHT,
      resizeHandles: RESIZE_HANDLES,
    })),
    xxs: layouts.xxs.map((item) => ({
      ...item,
      maxW: MAX_WIDTHS.xxs,
      minH: MIN_HEIGHT,
      resizeHandles: RESIZE_HANDLES,
    })),
  };
};
